// Import design tokens
import { COLORS } from '@presentation/theme/designTokens';
import { LIGHT_THEME } from '@presentation/theme/lightTheme';

export type LanguageCode = 'pt' | 'en' | 'es';
export const languages: Record<LanguageCode, any> = {
  pt: {
    code: 'pt',
    name: 'Português',
    flag: '🇧🇷',
    strings: {
      // ERRORS
      error: 'Erro',
      networkError: 'Erro de conexão. Verifique sua internet e tente novamente.',
      academyIdNotFound: 'Academia ID não encontrado',
      userProfileNotFound: 'Perfil do usuário não encontrado',
      classNotFound: 'Turma não encontrada',
      studentNotFound: 'Aluno não encontrado',
      dataLoadError: 'Não foi possível carregar os dados. Tente novamente.',
      saveError: 'Não foi possível salvar. Tente novamente.',
      deleteError: 'Não foi possível excluir. Tente novamente.',
      updateError: 'Não foi possível atualizar. Tente novamente.',
      permissionDenied: 'Permissão negada',
      sessionExpired: 'Sessão expirada',
      connectionTimeout: 'Tempo limite de conexão excedido',
      serverError: 'Erro no servidor. Tente novamente mais tarde.',
      validationError: 'Dados inválidos. Verifique os campos.',
      rateLimitExceeded: 'Muitas tentativas. Aguarde 5 minutos.',

      // ACTIONS
      create: 'Criar',
      add: 'Adicionar',
      edit: 'Editar',
      update: 'Atualizar',
      delete: 'Excluir',
      remove: 'Remover',
      search: 'Buscar',
      filter: 'Filtrar',
      sort: 'Ordenar',
      export: 'Exportar',
      import: 'Importar',
      share: 'Compartilhar',
      copy: 'Copiar',
      paste: 'Colar',
      duplicate: 'Duplicar',
      archive: 'Arquivar',
      restore: 'Restaurar',
      refresh: 'Atualizar',
      reload: 'Recarregar',
      reset: 'Redefinir',
      clear: 'Limpar',

      // STATUS
      active: 'Ativo',
      inactive: 'Inativo',
      pending: 'Pendente',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      expired: 'Expirado',
      valid: 'Válido',
      invalid: 'Inválido',
      invalidLinkOrCode: 'Link ou código de convite inválido',
      enabled: 'Habilitado',
      disabled: 'Desabilitado',
      available: 'Disponível',
      unavailable: 'Indisponível',
      visible: 'Visível',
      hidden: 'Oculto',

      // ACADEMY
      academy: 'Academia',
      student: 'Aluno',
      students: 'Alunos',
      instructor: 'Instrutor',
      instructors: 'Instrutores',
      class: 'Turma',
      classes: 'Turmas',
      graduation: 'Graduação',
      graduations: 'Graduações',
      belt: 'Faixa',
      belts: 'Faixas',
      modality: 'Modalidade',
      modalities: 'Modalidades',
      fightModalities: 'Modalidades de Luta',
      payment: 'Pagamento',
      payments: 'Pagamentos',
      schedule: 'Horário',
      schedules: 'Horários',
      lesson: 'Aula',
      lessons: 'Aulas',
      newClass: 'Nova Turma',
      noModalitiesRegistered: 'Nenhuma modalidade cadastrada',
      noModalityGoToAdmin: 'Nenhuma modalidade cadastrada. Vá em Admin > Modalidades para cadastrar antes de continuar.',

      // COMMON
      yes: 'Sim',
      all: 'Todos',
      no: 'Não',
      ok: 'OK',
      cancel: 'Cancelar',
      save: 'Salvar',
      close: 'Fechar',
      open: 'Abrir',
      loading: 'Carregando',
      saving: 'Salvando',
      processing: 'Processando',
      success: 'Sucesso',
      warning: 'Aviso',
      info: 'Informação',
      name: 'Nome',
      email: 'E-mail',
      phone: 'Telefone',
      address: 'Endereço',
      date: 'Data',
      time: 'Hora',
      at: 'às',
      description: 'Descrição',
      notes: 'Notas',
      total: 'Total',
      subtotal: 'Subtotal',
      discount: 'Desconto',
      fee: 'Taxa',
      free: 'Grátis',
      paid: 'Pago',
      overdue: 'Atrasado',
      currency: 'BRL',

      // NAVIGATION
      home: 'Início',
      dashboard: 'Painel',
      profile: 'Perfil',
      settings: 'Configurações',
      help: 'Ajuda',
      about: 'Sobre',
      logout: 'Sair',
      back: 'Voltar',
      next: 'Próximo',
      previous: 'Anterior',
      first: 'Primeiro',
      last: 'Último',

      // SETTINGS SCREEN
      account: 'Conta',
      editProfile: 'Editar Perfil',
      changePassword: 'Alterar Senha',
      demonstration: 'Demonstração',
      viewThemeDemo: 'Ver Demonstração de Temas',
      viewAvailableThemes: 'Visualize os temas disponíveis',
      preferences: 'Preferências',
      receivePushNotifications: 'Receber notificações push',
      darkMode: 'Modo Escuro',
      darkModeDescription: 'Tema escuro para academias de artes marciais',
      autoBackup: 'Backup Automático',
      autoBackupDescription: 'Backup automático dos seus dados',
      dataAndPrivacy: 'Dados e Privacidade',
      exportData: 'Exportar Dados',
      downloadDataCopy: 'Baixar uma cópia dos seus dados',
      appVersion: 'Versão do App',
      helpCenter: 'Central de Ajuda',
      sendFeedback: 'Enviar Feedback',
      dangerZone: 'Zona de Perigo',
      signOut: 'Sair',
      deleteAccount: 'Excluir Conta',
      confirmLogoutMessage: 'Tem certeza que deseja sair?',
      logoutError: 'Não foi possível fazer logout',
      inDevelopment: 'Em Desenvolvimento',
      exportDataDevelopment: 'Funcionalidade de exportação será implementada em breve',
      deleteAccountWarning: 'Esta ação é irreversível. Todos os seus dados serão perdidos.',
      deleteAccountDevelopment: 'Funcionalidade será implementada em breve',
      notInformed: 'Não informado',
      years: 'anos',
      since: 'Desde',
      memberSince: 'Membro desde',
      birthDate: 'Data de Nascimento',
      noClassesEnrolledSubtext: 'O aluno ainda não foi matriculado em nenhuma turma',
      loadingStudentProfile: 'Carregando perfil do aluno...',

      // PROFILE SCREEN
      personalInformation: 'Informações Pessoais',
      emergencyContact: 'Contato de Emergência',
      medicalInformation: 'Informações Médicas',
      allergiesMedicationsConditions: 'Alergias, medicamentos, condições médicas...',
      saveChanges: 'Salvar Alterações',
      profileUpdatedSuccess: 'Perfil atualizado com sucesso',
      cannotUpdateProfile: 'Não foi possível atualizar o perfil',
      academyInformation: 'Informações da Academia',
      currentPlan: 'Plano Atual',
      startDate: 'Data de Início',
      trainingsThisWeek: 'Treinos desta Semana',
      welcomeBackToAcademy: 'Bem-vindo de volta à academia',
      noTrainingThisWeek: 'Nenhum treino esta semana',
      trainingsThisYear: 'Treinos no Ano',
      contracts: 'Contratos',
      nextDueDate: 'Próximo Vencimento',
      checkInsThisWeek: 'Check-ins esta semana',
      physicalEvaluations: 'Avaliações Físicas',
      evaluationsRegistered: 'avaliações registradas',
      noEvaluationsRegistered: 'Nenhuma avaliação registrada',
      trackPhysicalProgress: 'Acompanhe seu progresso físico',
      myInjuries: 'Minhas Lesões',
      injuriesRegistered: 'lesões registradas',
      noInjuriesRegistered: 'Nenhuma lesão registrada',
      accountSettings: 'Configurações da Conta',
      clickToChangePassword: 'Clique para alterar sua senha',
      viewAllEvaluations: 'Ver todas as avaliações',
      notifications: 'Notificações',
      configureAppNotifications: 'Configure as notificações do app',
      privacyAndSecurity: 'Privacidade e Segurança',
      privacyLGPDSettings: 'Configurações de privacidade e LGPD',
      user: 'Usuário',
      confirmLogout: 'Confirmar Saída',
      paymentNearDue: 'Pagamento Próximo do Vencimento',
      paymentDueText: 'Seu plano {planName} vence em {days}',
      paymentDueToday: 'hoje',
      paymentDueTomorrow: 'amanhã',
      paymentDueInDays: 'dias',
      dateLabel: 'Data',
      valueLabel: 'Valor',
      changeDate: 'Alterar Data',
      payNow: 'Pagar Agora',
      loadingStudentData: 'Carregando dados do aluno',
      loadingPaymentData: 'Carregando dados de pagamento',
      checkingPaymentDue: 'Verificando vencimento de pagamento',
      nextEvaluationIn: 'Próxima avaliação em',
      viewFullCalendar: 'Ver Calendário Completo',
      noClassesScheduled: 'Nenhuma aula agendada',
      monthlyPayment: 'Mensalidade',
      attended: 'Presente',
      absent: 'Faltou',
      planName: 'Nome do Plano',

      // FORMS
      required: 'Obrigatório',
      optional: 'Opcional',
      select: 'Selecionar',
      choose: 'Escolher',
      upload: 'Enviar',
      download: 'Baixar',
      submit: 'Enviar',
      confirm: 'Confirmar',
      validate: 'Validar',
      verify: 'Verificar',

      // TIME
      today: 'Hoje',
      yesterday: 'Ontem',
      tomorrow: 'Amanhã',
      now: 'Agora mesmo',
      minutesAgo: 'minutos atrás',
      hoursAgo: 'horas atrás',
      daysAgo: 'dias atrás',
      weeksAgo: 'semanas atrás',
      monthsAgo: 'meses atrás',
      unknownDate: 'Data desconhecida',
      dataNotAvailable: 'Data não disponível',

      // ACTIVITIES
      newStudentRegistered: 'Novo aluno cadastrado',
      paymentReceived: 'Pagamento recebido',
      graduationRegistered: 'Graduação registrada',
      checkInRegistered: 'Check-in registrado',
      classScheduled: 'Aula agendada',
      announcementPosted: 'Aviso publicado',

      // DASHBOARD
      quickActions: 'Ações Rápidas',
      quickActionsSubtitle: 'Acesso direto às principais funcionalidades',
      checkIn: 'Check-in',
      checkIns: 'Check-ins',
      viewCalendar: 'Ver Calendário',
      viewReports: 'Ver Relatórios',
      manageStudents: 'Gerenciar Alunos',
      manageStudentsSubtitle: 'Gerenciar alunos',
      manageClasses: 'Gerenciar Turmas',
      manageClassesSubtitle: 'Gerenciar turmas',
      managePayments: 'Gerenciar Pagamentos',
      viewGraduations: 'Ver Graduações',
      viewSchedule: 'Visualizar cronograma',
      recentActivities: 'Atividades Recentes',
      viewAllActivities: 'Ver Todas as Atividades',
      calendar: 'Calendário',
      classSchedule: 'Cronograma das Turmas',
      management: 'Gestão',
      settingsManagement: 'Preferências e gestão',
      accessManagementReports: 'Acessar Gestão e Relatórios',
      myClasses: 'Minhas Turmas',
      classesToday: 'Aulas Hoje',
      todaySchedule: 'Agenda de Hoje',
      classesScheduled: 'aulas agendadas',
      manageClass: 'Gerenciar Turma',
      noClassesToday: 'Nenhuma aula hoje',
      planNextClasses: 'Planeje suas próximas aulas',
      directAccessFunctionalities: 'Acesso direto às funcionalidades',
      reports: 'Relatórios',
      dataAnalysis: 'Análise de dados',
      importantCommunications: 'Comunicações importantes',
      loadingAnnouncements: 'Carregando avisos',
      important: 'Importante',
      recentGraduations: 'Graduações Recentes',
      noRecentGraduations: 'Nenhuma graduação recente',
      viewAllGraduations: 'Ver todas',
      upcomingClasses: 'Próximas Aulas',
      scheduleNotDefined: 'Horário não definido',
      noUpcomingClasses: 'Nenhuma aula próxima',
      viewAllClasses: 'Ver todas as turmas',
      martialArtsInstructor: 'Instrutor de Artes Marciais',
      addClassScreen: 'Nova Turma',
      view: 'Visualizar',
      digitalAttendance: 'Chamada Digital',
      scheduleClasses: 'Agendar Aulas',
      addClassesToYourClasses: 'Adicione aulas às suas turmas',
      scheduleAction: 'Agendar',
      noClassesTitle: 'Nenhuma Turma',
      needOneClassToSchedule: 'Você precisa ter pelo menos uma turma criada para agendar aulas.',
      createClassAction: 'Criar Turma',

      // STUDENTS
      searchStudents: 'Buscar alunos...',
      allStudents: 'Todos os Alunos',
      allGenders: 'Todos os Gêneros',
      allModalities: 'Todas as Modalidades',
      clearFilters: 'Limpar Filtros',
      applyFilters: 'Aplicar Filtros',
      minAge: 'Idade Mínima',
      maxAge: 'Idade Máxima',
      enrollmentEnd: 'Fim da Matrícula',
      noStudentsFound: 'Nenhum aluno encontrado',
      noStudentsMessage: 'Tente ajustar os filtros ou adicione um novo aluno.',
      paymentPendingStudents: 'Pagamento Pendente',
      inactiveStudents: 'Alunos Inativos',
      male: 'Masculino',
      female: 'Feminino',
      other: 'Outro',
      paymentUpToDate: 'Em dia',
      paymentPending: 'Pendente',
      paymentOverdue: 'Atrasado',
      paymentNA: 'N/A',
      viewProfile: 'Ver Perfil',
      loadingStudentsInstructor: 'Carregando alunos do instrutor...',
      instructorDataLoaded: 'Dados do instrutor carregados com sucesso',
      generalErrorLoadingInstructorData: 'Erro geral ao carregar dados do instrutor',
      limitedInfoWarning: 'Não foi possível carregar todas as informações. Algumas funcionalidades podem estar limitadas.',
      sinceDate: 'Desde (AAAA-MM-DD)',
      status: 'Status',
      lastGraduation: 'Última graduação:',
      studentsSummary: 'Resumo dos Alunos',
      activeCount: 'Ativos',
      upToDate: 'Em Dia',
      withGraduation: 'Com Graduação',
      newStudent: 'Novo Aluno',

      // STUDENT DETAILS
      studentDetails: 'Detalhes do Aluno',
      phoneNotInformed: 'Telefone não informado',
      addressNotInformed: 'Endereço não informado',
      registeredAt: 'Registrado em',
      enrolledClasses: 'Turmas Matriculadas',
      graduationTimeline: 'Timeline de Graduações',
      financialSummary: 'Resumo Financeiro',
      totalPaid: 'Total Pago',
      recentPayments: 'Últimos Pagamentos',
      details: 'Detalhes',
      noClassesEnrolled: 'Nenhuma turma matriculada',
      paymentHistory: 'Histórico de Pagamentos',
      noPaymentsRegistered: 'Nenhum pagamento registrado',
      viewAllPayments: 'Ver Todos os Pagamentos',
      actions: 'Ações',
      editStudent: 'Editar Aluno',
      addGraduation: 'Adicionar Graduação',
      viewDetails: 'Ver Detalhes',
      disassociate: 'Desassociar',
      suspended: 'Suspenso',
      beginner: 'Iniciante',
      confirmDelete: 'Confirmar Exclusão',
      confirmDeleteStudent: 'Tem certeza que deseja excluir o aluno {name}?',
      studentDeletedSuccess: 'Aluno excluído com sucesso!',
      studentDeleteError: 'Erro ao excluir aluno',
      adjustSearchFilters: 'Ajuste os filtros de busca',
      addFirstStudent: 'Adicione o primeiro aluno',
      paymentOK: 'Pagamento OK',

      // CHECKIN

      unnamedClass: 'Turma sem nome',
      activeSessions: 'Sessões Ativas',
      stopCheckIn: 'Parar Check-in',
      todaysCheckIns: 'Check-ins de Hoje',
      noCheckInsToday: 'Nenhum check-in hoje',
      manualCheckIn: 'Check-in Manual',
      selectClass: 'Selecione a turma',
      searchStudent: 'Buscar aluno',
      selected: 'selecionados',
      selectAll: 'Selecionar Todos',
      present: 'Presente',
      manual: 'Manual',
      qrCode: 'QR Code',
      checkInStopped: 'Check-in parado com sucesso',
      successCheck: 'Check-in realizado com sucesso',
      selectClassFirst: 'Selecione uma turma primeiro',
      startCheckIn: 'Iniciar Check-in',


      // CLASS DETAILS
      confirmDeleteClass: 'Confirmar Exclusão',
      confirmDeleteClassMessage: 'Tem certeza que deseja excluir esta turma? Esta ação não pode ser desfeita e todos os alunos serão desvinculados.',
      classDeletedSuccess: 'Turma excluída com sucesso!',
      classDeleteError: 'Erro ao excluir turma',
      level: 'Nível',
      information: 'Informações',
      capacity: 'Capacidade',
      enrolledStudents: 'Alunos Matriculados',
      viewStudents: 'Ver Alunos',
      hideStudents: 'Ocultar Alunos',
      noStudentsEnrolled: 'Nenhum aluno matriculado',
      studentsWillAppearHere: 'Os alunos aparecerão aqui quando se matricularem',

      manage: 'Gerenciar',
      deleteClass: 'Excluir Turma',
      notDefined: 'Não definido',
      loadingClassDetails: 'Carregando detalhes da turma...',


      day: 'Dia',



      // MODALITIES & PLANS
      publish: 'Publicar',
      summary: 'Resumo',
      plans: 'Planos',
      paymentPlans: 'Planos de Pagamento',
      activeAnnouncements: 'Avisos Ativos',
      months: 'meses',
      noPlansRegistered: 'Nenhum plano registrado',
      noAnnouncementsPublished: 'Nenhum aviso publicado',
      noDescription: 'Sem descrição',
      deleting: 'Excluindo...',
      modalityUpdatedSuccess: 'Modalidade atualizada com sucesso!',
      modalityUpdateError: 'Erro ao atualizar modalidade',
      confirmDeleteModality: 'Tem certeza que deseja excluir a modalidade "{name}"?',
      modalityDeletedSuccess: 'Modalidade excluída com sucesso!',
      planUpdatedSuccess: 'Plano atualizado com sucesso!',
      planUpdateError: 'Erro ao atualizar plano',
      confirmDeletePlan: 'Tem certeza que deseja excluir o plano "{name}"?',
      planDeletedSuccess: 'Plano excluído com sucesso!',
      announcementUpdatedSuccess: 'Aviso atualizado com sucesso!',
      announcementUpdateError: 'Erro ao atualizar aviso',
      confirmDeleteAnnouncement: 'Tem certeza que deseja excluir o aviso "{title}"?',
      announcementDeletedSuccess: 'Aviso excluído com sucesso!',
      modalityNameRequired: 'Nome da modalidade é obrigatório',
      userNotAssociated: 'Usuário não associado a uma academia',
      modalityCreatedSuccess: 'Modalidade criada com sucesso!',
      errorCreatingModality: 'Erro ao criar modalidade',
      planNameAndValueRequired: 'Nome e valor do plano são obrigatórios',
      planCreatedSuccess: 'Plano criado com sucesso!',
      errorCreatingPlan: 'Erro ao criar plano',
      announcementTitleAndContentRequired: 'Título e conteúdo do aviso são obrigatórios',
      announcementPublishedSuccess: 'Aviso publicado com sucesso!',
      errorPublishingAnnouncement: 'Erro ao publicar aviso',
      nameNotInformed: 'Nome não informado',
      emailNotInformed: 'E-mail não informado',
      editPlan: 'Editar Plano',
      editAnnouncement: 'Editar Aviso',
      dateFormat: 'DD/MM/AAAA',

      // USER & ADMIN
      hello: 'Olá',
      admin: 'Admin',
      academyAdministrator: 'Administrador da Academia',
      online: 'Online',
      code: 'Código',

      // STATS
      totalStudents: 'Total de Alunos',
      activeStudents: 'Alunos Ativos',
      pendingPaymentsCount: 'Pendências',
      monthlyFinancials: 'Financeiro do Mês',
      monthlyRevenue: 'Receita do Mês',
      pendingCount: 'Pendentes',
      overdueCount: 'Atrasados',
      alerts: 'Alertas',
      paymentsOverdue: 'pagamento(s) em atraso',
      manyPendingPayments: 'Muitos pagamentos pendentes',
      loadingAcademyInfo: 'Carregando informações da academia...',

      // ANNOUNCEMENTS
      announcements: 'Avisos',
      announcementBoard: 'Mural de Avisos',
      noAnnouncementsNow: 'Nenhum aviso no momento',
      highPriority: 'Alta Prioridade',
      expiresOn: 'Expira em:',
      noExpirationDate: 'Sem data de expiração',

      // BELT LEVELS
      whiteBelt: 'Faixa Branca',
      yellowBelt: 'Faixa Amarela',
      orangeBelt: 'Faixa Laranja',
      greenBelt: 'Faixa Verde',
      blueBelt: 'Faixa Azul',
      purpleBelt: 'Faixa Roxa',
      brownBelt: 'Faixa Marrom',
      blackBelt: 'Faixa Preta',
      blackBelt1: 'Faixa Preta 1º Dan',
      blackBelt2: 'Faixa Preta 2º Dan',
      blackBelt3: 'Faixa Preta 3º Dan',
      blackBelt4: 'Faixa Preta 4º Dan',
      blackBelt5: 'Faixa Preta 5º Dan',

      // GRADUATION SCREEN
      newGraduation: 'Nova Graduação',
      currentGraduation: 'Graduação Atual',
      graduationInfo: 'Informações da Graduação',
      selectModality: 'Selecionar Modalidade',
      responsibleInstructor: 'Instrutor Responsável',
      selectInstructor: 'Selecionar Instrutor',
      newGraduationLabel: 'Nova Graduação',
      selectGraduation: 'Selecionar Graduação',
      additionalDetails: 'Detalhes Adicionais',
      graduationDate: 'Data da Graduação',
      addGraduationNotesPlaceholder: 'Adicione observações sobre a graduação...',
      certificateNumberOptional: 'Número do Certificado (Opcional)',
      certificatePlaceholder: 'Ex: CERT-2024-001',
      saveGraduation: 'Salvar Graduação',
      loadingModalities: 'Carregando modalidades...',
      noModalitiesFound: 'Nenhuma modalidade encontrada',
      unnamedGraduation: 'Graduação sem nome',
      noGraduationsAvailable: 'Nenhuma graduação disponível',
      loadingInstructors: 'Carregando instrutores...',
      unnamedInstructor: 'Instrutor sem nome',
      noInstructorsFound: 'Nenhum instrutor encontrado',
      academyNotFoundLogin: 'Academia não encontrada. Faça login novamente.',
      loadDataError: 'Não foi possível carregar os dados necessários',
      selectGraduationError: 'Por favor, selecione uma graduação',
      selectModalityError: 'Por favor, selecione uma modalidade',
      selectInstructorError: 'Por favor, selecione um instrutor responsável',
      selectDateError: 'Por favor, selecione uma data',
      futureDateError: 'A data da graduação não pode ser futura',
      certificateFormatError: 'Formato do certificado deve ser: CERT-YYYY-NNN (ex: CERT-2024-001)',
      graduationAddedSuccess: 'Graduação adicionada com sucesso!',
      selectModalityFirst: 'Selecione uma modalidade primeiro',
      invalidDate: 'Data inválida',
      selectDate: 'Selecionar data',

      // PHYSICAL EVALUATION
      physicalEvaluation: 'Avaliação Física',
      newPhysicalEvaluation: 'Nova Avaliação Física',
      editPhysicalEvaluation: 'Editar Avaliação Física',
      physicalEvaluationSubtitle: 'Registre suas medidas e acompanhe sua evolução física',
      basicMeasurements: 'Medidas Básicas',
      weightKg: 'Peso (kg)',
      heightCm: 'Altura (cm)',
      ageYears: 'Idade (anos)',
      bmiTitle: 'Índice de Massa Corporal (IMC)',
      bioimpedanceOptional: 'Bioimpedância (Opcional)',
      bodyFatPercent: 'Gordura Corporal (%)',
      muscleMassKg: 'Massa Muscular (kg)',
      boneMassKg: 'Massa Óssea (kg)',
      visceralFat: 'Gordura Visceral',
      basalMetabolismKcal: 'Metabolismo Basal (kcal)',
      bodyWaterPercent: 'Água Corporal (%)',
      observations: 'Observações',
      optionalObservations: 'Observações (Opcional)',
      observationsPlaceholder: 'Ex: Início de nova dieta, mudança no treino, etc.',
      weightRequired: 'Peso é obrigatório',
      weightInvalid: 'Peso deve ser um número válido maior que 0',
      heightRequired: 'Altura é obrigatória',
      heightInvalid: 'Altura deve ser um número válido maior que 0',
      ageRequired: 'Idade é obrigatória',
      ageInvalid: 'Idade deve ser um número válido entre 1 e 120',
      bodyFatInvalid: 'Percentual de gordura deve estar entre 0 e 100',
      muscleMassInvalid: 'Massa muscular deve ser um número válido maior que 0',
      bodyWaterInvalid: 'Percentual de água deve estar entre 0 e 100',
      academyNotIdentified: 'Erro: Academia não identificada. Faça login novamente.',
      evaluationUpdatedSuccess: 'Avaliação física atualizada com sucesso!',
      evaluationSavedSuccess: 'Avaliação física salva com sucesso!',
      evaluationSaveError: 'Erro ao salvar avaliação física. Tente novamente.',
      underweight: 'Abaixo do peso',
      normalWeight: 'Peso normal',
      overweight: 'Sobrepeso',
      obesityI: 'Obesidade grau I',
      obesityII: 'Obesidade grau II',
      obesityIII: 'Obesidade grau III',
      currentEvaluation: 'Avaliação Atual',
      progress: 'Progresso',
      vsPreviousEvaluation: 'vs. avaliação anterior',
      evolution: 'Evolução',
      evaluationHistory: 'Histórico de Avaliações',
      noEvaluationsFound: 'Nenhuma avaliação física encontrada',
      startEvaluationPrompt: 'Faça sua primeira avaliação para começar a acompanhar sua evolução',
      newEvaluation: 'Nova Avaliação',

      // MESSAGES
      functionalityInDevelopment: 'Funcionalidade em desenvolvimento',
      errorLoadingAnnouncements: 'Erro ao carregar anúncios',
      errorLoadingData: 'errorLoadingData',
      couldNotLoadAnnouncements: 'Não foi possível carregar os anúncios. Tente novamente mais tarde.',
      loadingInstructorDashboard: 'Carregando dashboard do instrutor',
      loadingStudentDashboard: 'Carregando dashboard do aluno',
      loadingAdminDashboard: 'Carregando dashboard do administrador',
      studentsLoaded: 'Alunos carregados',
      errorSearchingStudents: 'Erro ao buscar alunos',
      errorFormattingDate: 'Erro ao formatar data',
      couldNotLoadData: 'Não foi possível carregar os dados. Tente novamente.',
      tryAgainLater: 'Tente novamente mais tarde',

      // DAYS OF WEEK
      sunday: 'Domingo',
      monday: 'Segunda',
      tuesday: 'Terça',
      wednesday: 'Quarta',
      thursday: 'Quinta',
      friday: 'Sexta',
      saturday: 'Sábado',

      // MONTHS
      january: 'Janeiro',
      february: 'Fevereiro',
      march: 'Março',
      april: 'Abril',
      may: 'Maio',
      june: 'Junho',
      july: 'Julho',
      august: 'Agosto',
      september: 'Setembro',
      october: 'Outubro',
      november: 'Novembro',
      december: 'Dezembro',

      // MONTHS ABBREVIATED
      janShort: 'JAN',
      febShort: 'FEV',
      marShort: 'MAR',
      aprShort: 'ABR',
      mayShort: 'MAI',
      junShort: 'JUN',
      julShort: 'JUL',
      augShort: 'AGO',
      sepShort: 'SET',
      octShort: 'OUT',
      novShort: 'NOV',
      decShort: 'DEZ',
      daysOfWeekShort: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],

      // AUTH/LOGIN
      welcome: 'Bem-vindo de volta!',
      password: 'Senha',
      login: 'Entrar',
      forgotPassword: 'Esqueceu a senha?',
      orLoginWith: 'Ou entre com',
      noAccount: 'Não tem uma conta?',
      register: 'Cadastre-se',
      loggingIn: 'Entrando',
      loginSuccess: 'Login realizado com sucesso!',
      googleLoginSuccess: 'Login com Google realizado com sucesso!',
      facebookLoginSuccess: 'Login com Facebook realizado com sucesso!',
      microsoftLoginSuccess: 'Login com Microsoft realizado com sucesso!',
      appleLoginSuccess: 'Login com Apple realizado com sucesso!',
      invalidEmail: 'E-mail inválido',
      passwordTooShort: 'A senha é muito curta',
      passwordMinChars: 'Senha deve ter pelo menos 6 caracteres',
      fillAllFields: 'Preencha todos os campos',
      googleLoginError: 'Erro ao entrar com Google',
      facebookLoginError: 'Erro ao entrar com Facebook',
      appleLoginError: 'Erro ao entrar com Apple',
      microsoftLoginError: 'Erro ao entrar com Microsoft',

      // REGISTER
      createAccount: 'Criar conta',
      fillDataToRegister: 'Preencha seus dados para começar',
      personalData: 'Dados pessoais',
      fullName: 'Nome Completo',
      phoneWhatsApp: 'Telefone / WhatsApp',
      userType: 'Tipo de usuário',
      studentDescription: 'Acesse treinos e acompanhe seu progresso',
      instructorDescription: 'Gerencie turmas e alunos',
      administrator: 'Administrador',
      adminDescription: 'Gestão completa da academia',
      passwordSection: 'Segurança',
      confirmPassword: 'Confirmar Senha',
      alreadyHaveAccount: 'Já tem uma conta?',
      signIn: 'Entrar',
      creatingAccount: 'Criando sua conta',
      accountCreatedSuccess: 'Conta criada com sucesso!',
      registrationError: 'Erro ao criar conta',
      nameRequired: 'Nome é obrigatório',
      emailRequired: 'E-mail é obrigatório',
      passwordMinLength: 'Mínimo de 6 caracteres',
      passwordsMismatch: 'As senhas não coincidem',
      registrationDevelopment: 'Cadastro em desenvolvimento',
      acceptTermsRequired: 'Você deve aceitar os termos de uso',
      acceptPrivacyRequired: 'Você deve aceitar a política de privacidade',
      acceptThe: 'Aceito os',
      acceptPrivacy: 'Aceito a',
      termsOfUse: 'Termos de Uso',
      privacyPolicy: 'Política de Privacidade',
      emailAlreadyInUse: 'Este email já está cadastrado. Faça login ou use outro email.',
      weakPassword: 'Senha muito fraca. Use pelo menos 6 caracteres.',
      invalidEmailFormat: 'Email inválido. Verifique o formato.',

      // PASSWORD RECOVERY
      recoverPassword: 'Recuperar senha',
      enterEmailForInstructions: 'Digite seu e-mail para receber as instruções',
      pleaseValidEmail: 'Por favor, insira um e-mail válido',
      sendEmail: 'Enviar e-mail',
      emailSent: 'E-mail enviado',
      emailSentSuccess: 'E-mail de recuperação enviado com sucesso!',
      checkInboxInstructions: 'Verifique sua caixa de entrada para as instruções',
      spamFolderWarning: 'Não esqueça de verificar a pasta de spam',
      backToLogin: 'Voltar para o login',
      resetPasswordError: 'Erro ao enviar e-mail de recuperação',
      emailNotFound: 'E-mail não encontrado',
      tooManyRequests: 'Muitas solicitações. Tente mais tarde.',
      configurationNotFound: 'Configuração não encontrada',
      contactSupport: 'Entre em contato com o suporte',

      // INVITES
      invite: 'Convite',
      invites: 'Convites',
      inviteCode: 'Código de convite',
      inviteToken: 'Token de convite',
      inviteRequired: 'Código de convite é obrigatório',
      inviteInvalid: 'Código de convite inválido ou já utilizado',
      inviteExpired: 'Este convite expirou',
      inviteAccepted: 'Convite aceito com sucesso',
      inviteProcessingError: 'Erro ao processar o convite',
      inviteUnauthenticated: 'Usuário deve estar autenticado para usar um convite',
      inviteNotFound: 'Convite não encontrado',
      inviteAlreadyUsed: 'Este convite já foi utilizado',
      sendInvite: 'Enviar convite',
      createInvite: 'Criar convite',
      acceptInvite: 'Aceitar convite',
      invitationSent: 'Convite enviado',
      invitationAccepted: 'Convite aceito',

      // SYSTEM
      system: 'Sistema',
      colorWhite: '#FFFFFF'
    }
  },

  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    strings: {
      // ERRORS
      error: 'Error',
      networkError: 'Connection error. Check your internet and try again.',
      academyIdNotFound: 'Academy ID not found',
      userProfileNotFound: 'User profile not found',
      classNotFound: 'Class not found',
      studentNotFound: 'Student not found',
      dataLoadError: 'Could not load data. Please try again.',
      saveError: 'Could not save. Please try again.',
      deleteError: 'Could not delete. Please try again.',
      permissionDenied: 'Permission denied',
      sessionExpired: 'Session expired',
      connectionTimeout: 'Connection timeout exceeded',
      serverError: 'Server error. Please try again later.',
      validationError: 'Invalid data. Please check the fields.',
      rateLimitExceeded: 'Too many attempts. Please wait 5 minutes.',
      reload: 'Reload',
      reset: 'Reset',
      clear: 'Clear',

      // STATUS
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      completed: 'Completed',
      cancelled: 'Cancelled',
      expired: 'Expired',
      valid: 'Valid',
      invalid: 'Invalid',
      invalidLinkOrCode: 'Invalid invitation link or code',
      enabled: 'Enabled',
      disabled: 'Disabled',
      available: 'Available',
      unavailable: 'Unavailable',
      visible: 'Visible',
      hidden: 'Hidden',

      // ACADEMY
      academy: 'Academy',
      student: 'Student',
      students: 'Students',
      instructor: 'Instructor',
      instructors: 'Instructors',
      class: 'Class',
      classes: 'Classes',
      graduation: 'Graduation',
      graduations: 'Graduations',
      belt: 'Belt',
      belts: 'Belts',
      modality: 'Modality',
      modalities: 'Modalities',
      fightModalities: 'Fight Modalities',
      payment: 'Payment',
      payments: 'Payments',
      schedule: 'Schedule',
      schedules: 'Schedules',
      lesson: 'Lesson',
      lessons: 'Lessons',
      newClass: 'New Class',
      noModalitiesRegistered: 'No modalities registered',
      noModalityGoToAdmin: 'No modalities registered. Go to Admin > Modalities to register before continuing.',
      welcomeBackToAcademy: 'Welcome back to the academy',
      nextEvaluationIn: 'Next evaluation in',
      viewFullCalendar: 'View Full Calendar',
      noClassesScheduled: 'No classes scheduled',

      // COMMON
      yes: 'Yes',
      all: 'All',
      no: 'No',
      ok: 'OK',
      cancel: 'Cancel',
      save: 'Save',
      close: 'Close',
      open: 'Open',
      at: 'at',
      years: 'years',
      since: 'Since',
      memberSince: 'Member since',
      birthDate: 'Date of Birth',
      noClassesEnrolledSubtext: 'The student is not enrolled in any classes yet',
      loadingStudentProfile: 'Loading student profile...',
      loading: 'Loading...',
      saving: 'Saving...',
      processing: 'Processing...',
      success: 'Success',
      warning: 'Warning',
      info: 'Information',
      name: 'Name',
      email: 'email',
      phone: 'Phone',
      address: 'Address',
      date: 'Date',
      time: 'Time',
      description: 'Description',
      notes: 'Notes',
      total: 'Total',
      subtotal: 'Subtotal',
      discount: 'Discount',
      fee: 'Fee',
      free: 'Free',
      paid: 'Paid',
      overdue: 'Overdue',
      currency: 'USD',

      // NAVIGATION
      home: 'Home',
      dashboard: 'dashboard',
      profile: 'Profile',
      settings: 'Settings',
      help: 'Help',
      about: 'About',
      logout: 'Logout',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      first: 'First',
      last: 'Last',

      // SETTINGS SCREEN
      account: 'Account',
      editProfile: 'Edit Profile',
      changePassword: 'Change Password',
      demonstration: 'Demonstration',
      viewThemeDemo: 'View Theme Demo',
      viewAvailableThemes: 'View available themes',
      preferences: 'Preferences',
      receivePushNotifications: 'Receive push notifications',
      darkMode: 'Dark Mode',
      darkModeDescription: 'Dark theme for martial arts academies',
      autoBackup: 'Auto Backup',
      autoBackupDescription: 'Automatic backup of your data',
      dataAndPrivacy: 'Data and Privacy',
      exportData: 'Export Data',
      downloadDataCopy: 'Download a copy of your data',
      appVersion: 'App Version',
      helpCenter: 'Help Center',
      sendFeedback: 'Send Feedback',
      dangerZone: 'Danger Zone',
      signOut: 'Sign Out',
      deleteAccount: 'Delete Account',
      confirmLogoutMessage: 'Are you sure you want to log out?',
      logoutError: 'Could not log out',
      inDevelopment: 'In Development',
      exportDataDevelopment: 'Export functionality will be implemented soon',
      deleteAccountWarning: 'This action is irreversible. All your data will be lost.',
      deleteAccountDevelopment: 'Functionality will be implemented soon',
      notInformed: 'Not informed',

      // PROFILE SCREEN
      personalInformation: 'Personal Information',
      emergencyContact: 'Emergency Contact',
      medicalInformation: 'Medical Information',
      allergiesMedicationsConditions: 'Allergies, medications, medical conditions...',
      saveChanges: 'Save Changes',
      profileUpdatedSuccess: 'Profile updated successfully',
      cannotUpdateProfile: 'Could not update profile',
      academyInformation: 'Academy Information',
      currentPlan: 'Current Plan',
      startDate: 'Start Date',
      trainingsThisWeek: 'Trainings This Week',
      noTrainingThisWeek: 'No training this week',
      trainingsThisYear: 'Trainings This Year',
      contracts: 'Contracts',
      nextDueDate: 'Next Due Date',
      checkInsThisWeek: 'Check-ins this week',
      physicalEvaluations: 'Physical Evaluations',
      evaluationsRegistered: 'evaluations registered',
      noEvaluationsRegistered: 'No evaluations registered',
      trackPhysicalProgress: 'Track your physical progress',
      myInjuries: 'My Injuries',
      injuriesRegistered: 'injuries registered',
      noInjuriesRegistered: 'No injuries registered',
      accountSettings: 'Account Settings',
      clickToChangePassword: 'Click to change your password',
      viewAllEvaluations: 'View all evaluations',
      notifications: 'Notifications',
      configureAppNotifications: 'Configure app notifications',
      privacyAndSecurity: 'Privacy and Security',
      privacyLGPDSettings: 'Privacy and LGPD settings',
      user: 'User',
      confirmLogout: 'Confirm Logout',
      paymentNearDue: 'Payment Near Due',
      paymentDueText: 'Your {planName} plan is due in {days}',
      paymentDueToday: 'today',
      paymentDueTomorrow: 'tomorrow',
      paymentDueInDays: 'days',
      dateLabel: 'Date',
      valueLabel: 'Value',
      changeDate: 'Change Date',
      payNow: 'Pay Now',
      loadingStudentData: 'Loading student data',
      loadingPaymentData: 'Loading payment data',
      checkingPaymentDue: 'Checking payment due',
      monthlyPayment: 'Monthly Payment',
      attended: 'Attended',
      absent: 'Absent',
      // FORMS
      required: 'Required',
      optional: 'Optional',
      select: 'Select',
      choose: 'Choose',
      upload: 'Upload',
      download: 'Download',
      submit: 'Submit',
      confirm: 'Confirm',
      validate: 'Validate',
      verify: 'Verify',

      // TIME
      today: 'Today',
      yesterday: 'Yesterday',
      tomorrow: 'Tomorrow',
      now: 'Just now',
      minutesAgo: 'minutes ago',
      hoursAgo: 'hours ago',
      daysAgo: 'days ago',
      weeksAgo: 'weeks ago',
      monthsAgo: 'months ago',
      unknownDate: 'Unknown date',
      dataNotAvailable: 'Date not available',

      // ACTIVITIES
      newStudentRegistered: 'New student registered',
      paymentReceived: 'Payment received',
      graduationRegistered: 'Graduation registered',
      checkInRegistered: 'Check-in registered',
      classScheduled: 'Class scheduled',
      announcementPosted: 'Announcement posted',

      // DASHBOARD
      quickActions: 'Quick Actions',
      quickActionsSubtitle: 'Direct access to main features',
      checkIn: 'Check-in',
      viewCalendar: 'View Calendar',
      viewReports: 'View Reports',
      manageStudents: 'Manage Students',
      manageStudentsSubtitle: 'Manage students',
      manageClasses: 'Manage Classes',
      manageClassesSubtitle: 'Manage classes',
      managePayments: 'Manage Payments',
      viewGraduations: 'View Graduations',
      viewSchedule: 'View schedule',
      recentActivities: 'Recent Activities',
      viewAllActivities: 'View All Activities',
      calendar: 'Calendar',
      classSchedule: 'Class Schedule',
      management: 'Management',
      settingsManagement: 'Preferences and management',
      accessManagementReports: 'Access Management and Reports',


      // CHECKIN
      myClasses: 'My Classes',
      unnamedClass: 'Unnamed Class',
      activeSessions: 'Active Sessions',
      stopCheckIn: 'Stop Check-in',
      todaysCheckIns: "Today's Check-ins",
      noCheckInsToday: 'No check-ins today',
      manualCheckIn: 'Manual Check-in',
      selectClass: 'Select class',
      searchStudent: 'Search student',
      selected: 'selected',
      selectAll: 'Select All',
      present: 'Present',
      manual: 'Manual',
      qrCode: 'QR Code',
      checkInStopped: 'Check-in stopped successfully',
      successCheck: 'Check-in successful',
      selectClassFirst: 'Select a class first',
      startCheckIn: 'Start Check-in',


      // CLASS DETAILS
      confirmDeleteClass: 'Confirm Delete',
      confirmDeleteClassMessage: 'Are you sure you want to delete this class? This action cannot be undone and all students will be unlinked.',
      classDeletedSuccess: 'Class deleted successfully!',
      classDeleteError: 'Error deleting class',
      level: 'Level',
      information: 'Information',
      capacity: 'Capacity',
      enrolledStudents: 'Enrolled Students',
      viewStudents: 'View Students',
      hideStudents: 'Hide Students',
      noStudentsEnrolled: 'No students enrolled',
      studentsWillAppearHere: 'Students will appear here when they enroll',

      manage: 'Manage',
      deleteClass: 'Delete Class',
      notDefined: 'Not defined',
      loadingClassDetails: 'Loading class details...',


      day: 'Day',
      viewProfile: 'View Profile',
      checkIns: 'Check-ins',

      // MODALITIES & PLANS
      publish: 'Publish',
      summary: 'Summary',
      plans: 'Plans',
      paymentPlans: 'Payment Plans',
      activeAnnouncements: 'Active Announcements',
      months: 'months',
      noPlansRegistered: 'No plans registered',
      noAnnouncementsPublished: 'No announcements published',
      noDescription: 'No description',
      deleting: 'Deleting...',
      modalityUpdatedSuccess: 'Modality updated successfully!',
      modalityUpdateError: 'Error updating modality',
      confirmDeleteModality: 'Are you sure you want to delete modality "{name}"?',
      modalityDeletedSuccess: 'Modality deleted successfully!',
      planUpdatedSuccess: 'Plan updated successfully!',
      planUpdateError: 'Error updating plan',
      confirmDeletePlan: 'Are you sure you want to delete plan "{name}"?',
      planDeletedSuccess: 'Plan deleted successfully!',
      announcementUpdatedSuccess: 'Announcement updated successfully!',
      announcementUpdateError: 'Error updating announcement',
      confirmDeleteAnnouncement: 'Are you sure you want to delete announcement "{title}"?',
      announcementDeletedSuccess: 'Announcement deleted successfully!',
      modalityNameRequired: 'Modality name is required',
      userNotAssociated: 'User not associated with an academy',
      modalityCreatedSuccess: 'Modality created successfully!',
      errorCreatingModality: 'Error creating modality',
      planNameAndValueRequired: 'Plan name and value are required',
      planCreatedSuccess: 'Plan created successfully!',
      errorCreatingPlan: 'Error creating plan',
      announcementTitleAndContentRequired: 'Announcement title and content are required',
      announcementPublishedSuccess: 'Announcement published successfully!',
      errorPublishingAnnouncement: 'Error publishing announcement',
      nameNotInformed: 'Name not informed',
      emailNotInformed: 'Email not informed',
      editPlan: 'Edit Plan',
      editAnnouncement: 'Edit Announcement',
      dateFormat: 'MM/DD/YYYY',

      // USER & ADMIN
      hello: 'Hello',
      admin: 'Admin',
      academyAdministrator: 'Academy Administrator',
      online: 'Online',
      code: 'Code',

      // STATS
      totalStudents: 'Total Students',
      activeStudents: 'Active Students',

      // STUDENT DETAILS
      studentDetails: 'Student Details',
      phoneNotInformed: 'Phone not informed',
      addressNotInformed: 'Address not informed',
      registeredAt: 'Registered at',
      enrolledClasses: 'Enrolled Classes',
      graduationTimeline: 'Graduation Timeline',
      financialSummary: 'Financial Summary',
      totalPaid: 'Total Paid',
      recentPayments: 'Recent Payments',
      details: 'Details',
      noClassesEnrolled: 'No classes enrolled',
      paymentHistory: 'Payment History',
      noPaymentsRegistered: 'No payments registered',
      viewAllPayments: 'View All Payments',
      actions: 'Actions',
      editStudent: 'Edit Student',
      addGraduation: 'Add Graduation',
      viewDetails: 'View Details',
      disassociate: 'Disassociate',
      suspended: 'Suspended',
      beginner: 'Beginner',
      confirmDelete: 'Confirm Delete',
      confirmDeleteStudent: 'Are you sure you want to delete student {name}?',
      studentDeletedSuccess: 'Student deleted successfully!',
      studentDeleteError: 'Error deleting student',
      adjustSearchFilters: 'Adjust search filters',
      addFirstStudent: 'Add the first student',
      paymentOK: 'Payment OK',
      planName: 'Plan Name',
      pendingPaymentsCount: 'Pending',
      monthlyFinancials: 'Monthly Financials',
      monthlyRevenue: 'Monthly Revenue',
      pendingCount: 'Pending',
      overdueCount: 'Overdue',
      alerts: 'Alerts',
      paymentsOverdue: 'overdue payment(s)',
      manyPendingPayments: 'Many pending payments',
      loadingAcademyInfo: 'Loading academy information...',

      // ANNOUNCEMENTS
      announcements: 'Announcements',
      announcementBoard: 'Announcement Board',
      noAnnouncementsNow: 'No announcements at the moment',
      highPriority: 'High Priority',
      expiresOn: 'Expires on:',
      noExpirationDate: 'No expiration date',

      // BELT LEVELS
      whiteBelt: 'White Belt',
      yellowBelt: 'Yellow Belt',
      orangeBelt: 'Orange Belt',
      greenBelt: 'Green Belt',
      blueBelt: 'Blue Belt',
      purpleBelt: 'Purple Belt',
      brownBelt: 'Brown Belt',
      blackBelt: 'Black Belt',
      blackBelt1: 'Black Belt 1st Dan',
      blackBelt2: 'Black Belt 2nd Dan',
      blackBelt3: 'Black Belt 3rd Dan',
      blackBelt4: 'Black Belt 4th Dan',
      blackBelt5: 'Black Belt 5th Dan',

      // GRADUATION SCREEN
      newGraduation: 'New Graduation',
      currentGraduation: 'Current Graduation',
      graduationInfo: 'Graduation Information',
      selectModality: 'Select Modality',
      responsibleInstructor: 'Responsible Instructor',
      selectInstructor: 'Select Instructor',
      newGraduationLabel: 'New Graduation',
      selectGraduation: 'Select Graduation',
      additionalDetails: 'Additional Details',
      graduationDate: 'Graduation Date',
      addGraduationNotesPlaceholder: 'Add notes about the graduation...',
      certificateNumberOptional: 'Certificate Number (Optional)',
      certificatePlaceholder: 'Ex: CERT-2024-001',
      saveGraduation: 'Save Graduation',
      loadingModalities: 'Loading modalities...',
      noModalitiesFound: 'No modalities found',
      unnamedGraduation: 'Unnamed Graduation',
      noGraduationsAvailable: 'No graduations available',
      loadingInstructors: 'Loading instructors...',
      unnamedInstructor: 'Unnamed Instructor',
      noInstructorsFound: 'No instructors found',
      academyNotFoundLogin: 'Academy not found. Please login again.',
      loadDataError: 'Could not load necessary data',
      selectGraduationError: 'Please select a graduation',
      selectModalityError: 'Please select a modality',
      selectInstructorError: 'Please select a responsible instructor',
      selectDateError: 'Please select a date',
      futureDateError: 'Graduation date cannot be in the future',
      certificateFormatError: 'Certificate format must be: CERT-YYYY-NNN (ex: CERT-2024-001)',
      graduationAddedSuccess: 'Graduation added successfully!',
      selectModalityFirst: 'Select a modality first',
      invalidDate: 'Invalid date',
      selectDate: 'Select date',

      // PHYSICAL EVALUATION
      physicalEvaluation: 'Physical Evaluation',
      newPhysicalEvaluation: 'New Physical Evaluation',
      editPhysicalEvaluation: 'Edit Physical Evaluation',
      physicalEvaluationSubtitle: 'Record your measurements and track your physical progress',
      basicMeasurements: 'Basic Measurements',
      weightKg: 'Weight (kg)',
      heightCm: 'Height (cm)',
      ageYears: 'Age (years)',
      bmiTitle: 'Body Mass Index (BMI)',
      bioimpedanceOptional: 'Bioimpedance (Optional)',
      bodyFatPercent: 'Body Fat (%)',
      muscleMassKg: 'Muscle Mass (kg)',
      boneMassKg: 'Bone Mass (kg)',
      visceralFat: 'Visceral Fat',
      basalMetabolismKcal: 'Basal Metabolism (kcal)',
      bodyWaterPercent: 'Body Water (%)',
      observations: 'Observations',
      optionalObservations: 'Observations (Optional)',
      observationsPlaceholder: 'Ex: Started new diet, changed workout, etc.',
      weightRequired: 'Weight is required',
      weightInvalid: 'Weight must be a valid number greater than 0',
      heightRequired: 'Height is required',
      heightInvalid: 'Height must be a valid number greater than 0',
      ageRequired: 'Age is required',
      ageInvalid: 'Age must be a valid number between 1 and 120',
      bodyFatInvalid: 'Body fat percentage must be between 0 and 100',
      muscleMassInvalid: 'Muscle mass must be a valid number greater than 0',
      bodyWaterInvalid: 'Body water percentage must be between 0 and 100',
      academyNotIdentified: 'Error: Academy not identified. Please login again.',
      evaluationUpdatedSuccess: 'Physical evaluation updated successfully!',
      evaluationSavedSuccess: 'Physical evaluation saved successfully!',
      evaluationSaveError: 'Error saving physical evaluation. Please try again.',
      underweight: 'Underweight',
      normalWeight: 'Normal weight',
      overweight: 'Overweight',
      obesityI: 'Obesity class I',
      obesityII: 'Obesity class II',
      obesityIII: 'Obesity class III',
      currentEvaluation: 'Current Evaluation',
      progress: 'Progress',
      vsPreviousEvaluation: 'vs. previous evaluation',
      evolution: 'Evolution',
      evaluationHistory: 'Evaluation History',
      noEvaluationsFound: 'No physical evaluations found',
      startEvaluationPrompt: 'Make your first evaluation to start tracking your progress',
      newEvaluation: 'New Evaluation',

      // MESSAGES
      functionalityInDevelopment: 'Feature under development',
      errorLoadingAnnouncements: 'Error loading announcements',
      errorLoadingData: 'Error loading data',
      couldNotLoadAnnouncements: 'Could not load announcements. Please try again later.',
      loadingInstructorDashboard: 'Loading instructor dashboard',
      loadingStudentDashboard: 'Loading student dashboard',
      loadingAdminDashboard: 'Loading admin dashboard',
      studentsLoaded: 'Students loaded',
      errorSearchingStudents: 'Error searching students',
      errorFormattingDate: 'Error formatting date',
      couldNotLoadData: 'Could not load data. Please try again.',
      tryAgainLater: 'Please try again later',

      // MONTHS ABBREVIATED
      janShort: 'JAN',
      febShort: 'FEB',
      marShort: 'MAR',
      aprShort: 'APR',
      mayShort: 'MAY',
      junShort: 'JUN',
      julShort: 'JUL',
      augShort: 'AUG',
      sepShort: 'SEP',
      octShort: 'OCT',
      novShort: 'NOV',
      decShort: 'DEC',
      daysOfWeekShort: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],

      // AUTH/LOGIN
      welcome: 'Welcome back!',
      password: 'Password',
      login: 'Login',
      forgotPassword: 'Forgot password?',
      orLoginWith: 'Or login with',
      noAccount: "Don't have an account?",
      register: 'Sign up',
      loggingIn: 'Logging in',
      loginSuccess: 'Login successful!',
      googleLoginSuccess: 'Google login successful!',
      facebookLoginSuccess: 'Facebook login successful!',
      microsoftLoginSuccess: 'Microsoft login successful!',
      appleLoginSuccess: 'Apple login successful!',
      invalidEmail: 'Invalid email',
      passwordTooShort: 'Password too short',
      passwordMinChars: 'Password must be at least 6 characters',
      fillAllFields: 'Please fill all fields',
      googleLoginError: 'Google login error',
      facebookLoginError: 'Facebook login error',
      appleLoginError: 'Apple login error',
      microsoftLoginError: 'Microsoft login error',

      // REGISTER
      createAccount: 'Create account',
      fillDataToRegister: 'Fill in your details to get started',
      personalData: 'Personal data',
      fullName: 'Full Name',
      phoneWhatsApp: 'Phone / WhatsApp',
      userType: 'User type',
      studentDescription: 'Access workouts and track your progress',
      instructorDescription: 'Manage classes and students',
      administrator: 'Administrator',
      adminDescription: 'Complete gym management',
      passwordSection: 'Security',
      confirmPassword: 'Confirm Password',
      alreadyHaveAccount: 'Already have an account?',
      signIn: 'Sign in',
      creatingAccount: 'Creating your account',
      accountCreatedSuccess: 'Account created successfully!',
      registrationError: 'Error creating account',
      nameRequired: 'Name is required',
      emailRequired: 'Email is required',
      passwordMinLength: 'Minimum 6 characters',
      passwordsMismatch: 'Passwords do not match',
      registrationDevelopment: 'Registration under development',
      acceptTermsRequired: 'You must accept the terms of use',
      acceptPrivacyRequired: 'You must accept the privacy policy',
      acceptThe: 'I accept the',
      acceptPrivacy: 'I accept the',
      termsOfUse: 'Terms of Use',
      privacyPolicy: 'Privacy Policy',
      emailAlreadyInUse: 'This email is already registered. Please login or use another email.',
      weakPassword: 'Password too weak. Use at least 6 characters.',
      invalidEmailFormat: 'Invalid email. Check the format.',

      // PASSWORD RECOVERY
      recoverPassword: 'Recover password',
      enterEmailForInstructions: 'Enter your email to receive instructions',
      pleaseValidEmail: 'Please enter a valid email',
      sendEmail: 'Send email',
      emailSent: 'Email sent',
      emailSentSuccess: 'Recovery email sent successfully!',
      checkInboxInstructions: 'Check your inbox for instructions',
      spamFolderWarning: "Don't forget to check the spam folder",
      backToLogin: 'Back to login',
      resetPasswordError: 'Error sending recovery email',
      emailNotFound: 'Email not found',
      tooManyRequests: 'Too many requests. Try later.',
      configurationNotFound: 'Configuration not found',
      contactSupport: 'Contact support',

      // INVITES
      invite: 'Invite',
      invites: 'Invites',
      inviteCode: 'Invite code',
      inviteToken: 'Invite token',
      inviteRequired: 'Invite code is required',
      inviteInvalid: 'Invalid or already used invite code',
      inviteExpired: 'This invite has expired',
      inviteAccepted: 'Invite accepted successfully',
      inviteProcessingError: 'Error processing invite',
      inviteUnauthenticated: 'User must be authenticated to use an invite',
      inviteNotFound: 'Invite not found',
      inviteAlreadyUsed: 'This invite has already been used',
      sendInvite: 'Send invite',
      createInvite: 'Create invite',
      acceptInvite: 'Accept invite',
      invitationSent: 'Invitation sent',
      invitationAccepted: 'Invitation accepted',
    }
  },

  es: {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    strings: {
      // ERRORS
      error: 'Error',
      networkError: 'Error de conexión. Verifique su internet e intente nuevamente.',
      academyIdNotFound: 'ID de academia no encontrado',
      userProfileNotFound: 'Perfil de usuario no encontrado',
      classNotFound: 'Clase no encontrada',
      studentNotFound: 'Estudiante no encontrado',
      dataLoadError: 'No se pudieron cargar los datos. Intente nuevamente.',
      saveError: 'No se pudo guardar. Intente nuevamente.',
      deleteError: 'No se pudo eliminar. Intente nuevamente.',
      updateError: 'No se pudo actualizar. Intente nuevamente.',
      permissionDenied: 'Permiso denegado',
      sessionExpired: 'Sesión expirada',
      connectionTimeout: 'Tiempo límite de conexión excedido',
      serverError: 'Error del servidor. Intente nuevamente más tarde.',
      validationError: 'Datos inválidos. Verifique los campos.',
      rateLimitExceeded: 'Demasiados intentos. Espere 5 minutos.',

      // ACTIONS
      create: 'Crear',
      add: 'Agregar',
      edit: 'edit',
      update: 'Actualizar',
      delete: 'Eliminar',
      remove: 'Remover',
      search: 'search',
      filter: 'filter',
      sort: 'Ordenar',
      export: 'Exportar',
      import: 'Importar',
      share: 'Compartir',
      copy: 'Copiar',
      paste: 'Pegar',
      duplicate: 'Duplicar',
      archive: 'Archivar',
      restore: 'Restaurar',
      refresh: 'Actualizar',
      reload: 'Recargar',
      reset: 'Restablecer',
      clear: 'Limpiar',

      // STATUS
      active: 'Activo',
      inactive: 'Inactivo',
      pending: 'Pendiente',
      completed: 'Completado',
      cancelled: 'cancelled',
      expired: 'Expirado',
      valid: 'Válido',
      invalid: 'Inválido',
      invalidLinkOrCode: 'Link o código de invitación inválido',
      enabled: 'Habilitado',
      disabled: 'Deshabilitado',
      available: 'Disponible',
      unavailable: 'No disponible',
      visible: 'Visible',
      hidden: 'Oculto',

      // ACADEMY
      academy: 'academy',
      student: 'Estudiante',
      students: 'Estudiantes',
      instructor: 'Instructor',
      instructors: 'Instructores',
      class: 'Clase',
      classes: 'Clases',
      graduation: 'Graduación',
      graduations: 'Graduaciones',
      belt: 'Cinturón',
      belts: 'Cinturones',
      modality: 'Modalidad',
      modalities: 'Modalidades',
      fightModalities: 'Modalidades de Lucha',
      payment: 'Pago',
      payments: 'Pagos',
      schedule: 'Horario',
      schedules: 'Horarios',
      lesson: 'Lección',
      lessons: 'Lecciones',
      newClass: 'Nueva Clase',
      noModalitiesRegistered: 'Ninguna modalidad registrada',
      noModalityGoToAdmin: 'Ninguna modalidad registrada. Vaya a Admin > Modalidades para registrar antes de continuar.',

      // COMMON
      yes: 'Sí',
      all: 'Todos',
      no: 'No',
      ok: 'OK',
      cancel: 'cancel',
      save: 'Guardar',
      close: 'Cerrar',
      open: 'open',
      loading: 'Cargando...',
      saving: 'Guardando...',
      processing: 'Procesando...',
      success: 'Éxito',
      warning: 'Advertencia',
      info: 'Información',
      name: 'Nombre',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      address: 'Dirección',
      date: 'Fecha',
      time: 'time',
      description: 'Descripción',
      notes: 'Observaciones',
      total: 'Total',
      subtotal: 'Subtotal',
      discount: 'Descuento',
      fee: 'Tarifa',
      free: 'Gratis',
      paid: 'Pagado',
      overdue: 'Vencido',
      currency: 'EUR',

      // NAVIGATION
      home: 'Inicio',
      dashboard: 'Panel',
      profile: 'profile',
      settings: 'Configuraciones',
      help: 'Ayuda',
      about: 'Acerca de',
      logout: 'Cerrar sesión',
      back: 'Atrás',
      next: 'Siguiente',
      previous: 'previous',
      first: 'Primero',
      last: 'Último',

      // PROFILE SCREEN
      personalInformation: 'Información Personal',
      emergencyContact: 'Contacto de Emergencia',
      medicalInformation: 'Información Médica',
      allergiesMedicationsConditions: 'Alergias, medicamentos, condiciones médicas...',
      saveChanges: 'Guardar Cambios',
      profileUpdatedSuccess: 'Perfil actualizado con éxito',
      cannotUpdateProfile: 'No se pudo actualizar el perfil',
      academyInformation: 'Información de la Academia',
      currentPlan: 'Plan Actual',
      startDate: 'Fecha de Inicio',
      trainingsThisWeek: 'Entrenamientos Esta Semana',
      noTrainingThisWeek: 'Ningún entrenamiento esta semana',
      trainingsThisYear: 'Entrenamientos Este Año',
      attended: 'Asistió',
      absent: 'Faltó',
      contracts: 'Contratos',
      nextDueDate: 'Próximo Vencimiento',
      checkInsThisWeek: 'Check-ins esta semana',
      physicalEvaluations: 'Evaluaciones Físicas',
      evaluationsRegistered: 'evaluaciones registradas',
      noEvaluationsRegistered: 'Ninguna evaluación registrada',
      trackPhysicalProgress: 'Siga su progreso físico',
      myInjuries: 'Mis Lesiones',
      injuriesRegistered: 'lesiones registradas',
      noInjuriesRegistered: 'Ninguna lesión registrada',
      accountSettings: 'Configuración de la Cuenta',
      clickToChangePassword: 'Haga clic para cambiar su contraseña',
      viewAllEvaluations: 'Ver todas las evaluaciones',
      notifications: 'Notificaciones',
      configureAppNotifications: 'Configure las notificaciones de la app',
      privacyAndSecurity: 'Privacidad y Seguridad',
      privacyLGPDSettings: 'Configuración de privacidad y LGPD',
      user: 'Usuario',
      confirmLogout: 'Confirmar Salida',
      paymentNearDue: 'Pago Próximo a Vencer',
      paymentDueText: 'Su plan {planName} vence en {days}',
      paymentDueToday: 'hoy',
      paymentDueTomorrow: 'mañana',
      paymentDueInDays: 'días',
      dateLabel: 'Fecha',
      valueLabel: 'Valor',
      changeDate: 'Cambiar Fecha',
      payNow: 'Pagar Ahora',
      loadingStudentData: 'Cargando datos del estudiante',
      loadingPaymentData: 'Cargando datos de pago',
      checkingPaymentDue: 'Verificando vencimiento de pago',
      monthlyPayment: 'Mensualidad',

      // FORMS
      required: 'Requerido',
      optional: 'Opcional',
      select: 'Seleccionar',
      choose: 'Elegir',
      upload: 'Subir',
      download: 'Descargar',
      submit: 'Enviar',
      confirm: 'confirm',
      validate: 'Validar',
      verify: 'Verificar',

      // TIME
      today: 'Hoy',
      yesterday: 'Ayer',
      tomorrow: 'Mañana',
      now: 'Ahora mismo',
      minutesAgo: 'minutos atrás',
      hoursAgo: 'horas atrás',
      daysAgo: 'días atrás',
      weeksAgo: 'semanas atrás',
      monthsAgo: 'meses atrás',
      unknownDate: 'Fecha desconocida',
      dataNotAvailable: 'Fecha no disponible',

      // ACTIVITIES
      newStudentRegistered: 'Nuevo estudiante registrado',
      paymentReceived: 'Pago recibido',
      graduationRegistered: 'Graduación registrada',
      checkInRegistered: 'Check-in registrado',
      classScheduled: 'Clase programada',
      announcementPosted: 'Aviso publicado',

      // DASHBOARD
      quickActions: 'Acciones Rápidas',
      quickActionsSubtitle: 'Acceso directo a las principales funcionalidades',
      checkIn: 'Check-in',
      viewCalendar: 'Ver Calendario',
      viewReports: 'Ver Informes',
      manageStudents: 'Gestionar Estudiantes',
      manageStudentsSubtitle: 'Gestionar estudiantes',
      manageClasses: 'Gestionar Clases',
      manageClassesSubtitle: 'Gestionar clases',
      managePayments: 'Gestionar Pagos',
      viewGraduations: 'Ver Graduaciones',
      viewSchedule: 'Ver cronograma',
      recentActivities: 'Actividades Recientes',
      viewAllActivities: 'Ver Todas las Actividades',
      calendar: 'Calendario',
      classSchedule: 'Cronograma de Clases',
      management: 'Gestión',
      settingsManagement: 'Preferencias y gestión',
      accessManagementReports: 'Acceder a Gestión e Informes',


      // CHECKIN
      myClasses: 'Mis Clases',
      unnamedClass: 'Clase sin nombre',
      activeSessions: 'Sesiones Activas',
      stopCheckIn: 'Detener Check-in',
      todaysCheckIns: 'Check-ins de Hoy',
      noCheckInsToday: 'Ningún check-in hoy',
      manualCheckIn: 'Check-in Manual',
      selectClass: 'Seleccione la clase',
      searchStudent: 'Buscar estudiante',
      selected: 'seleccionados',
      selectAll: 'Seleccionar Todos',
      present: 'Presente',
      manual: 'Manual',
      qrCode: 'Código QR',
      checkInStopped: 'Check-in detenido con éxito',
      successCheck: 'Check-in realizado con éxito',
      selectClassFirst: 'Seleccione una clase primero',
      startCheckIn: 'Iniciar Check-in',


      // CLASS DETAILS
      confirmDeleteClass: 'Confirmar Eliminación',
      confirmDeleteClassMessage: '¿Está seguro de que desea eliminar esta clase? Esta acción no se puede deshacer y todos los estudiantes serán desvinculados.',
      classDeletedSuccess: '¡Clase eliminada con éxito!',
      classDeleteError: 'Error al eliminar clase',
      level: 'Nivel',
      information: 'Información',
      capacity: 'Capacidad',
      enrolledStudents: 'Estudiantes Matriculados',
      viewStudents: 'Ver Estudiantes',
      hideStudents: 'Ocultar Estudiantes',
      noStudentsEnrolled: 'Ningún estudiante matriculado',
      studentsWillAppearHere: 'Los estudiantes aparecerán aquí cuando se matriculen',

      manage: 'Gestionar',
      deleteClass: 'Eliminar Clase',
      notDefined: 'No definido',
      loadingClassDetails: 'Cargando detalles de la clase...',


      day: 'Día',
      viewProfile: 'Ver Perfil',
      checkIns: 'Check-ins',

      // MODALITIES & PLANS
      publish: 'Publicar',
      summary: 'Resumen',
      plans: 'Planes',
      paymentPlans: 'Planes de Pago',
      activeAnnouncements: 'Avisos Activos',
      months: 'meses',
      noPlansRegistered: 'Ningún plan registrado',
      noAnnouncementsPublished: 'Ningún aviso publicado',
      noDescription: 'Sin descripción',
      deleting: 'Eliminando...',
      modalityUpdatedSuccess: '¡Modalidad actualizada con éxito!',
      modalityUpdateError: 'Error al actualizar modalidad',
      confirmDeleteModality: '¿Está seguro de que desea eliminar la modalidad "{name}"?',
      modalityDeletedSuccess: '¡Modalidad eliminada con éxito!',
      planUpdatedSuccess: '¡Plan actualizado con éxito!',
      planUpdateError: 'Error al actualizar plan',
      confirmDeletePlan: '¿Está seguro de que desea eliminar el plan "{name}"?',
      planDeletedSuccess: '¡Plan eliminado con éxito!',
      announcementUpdatedSuccess: '¡Aviso actualizado con éxito!',
      announcementUpdateError: 'Error al actualizar aviso',
      confirmDeleteAnnouncement: '¿Está seguro de que desea eliminar el aviso "{title}"?',
      announcementDeletedSuccess: '¡Aviso eliminado con éxito!',
      modalityNameRequired: 'El nombre de la modalidad es obligatorio',
      userNotAssociated: 'Usuario no asociado a una academia',
      modalityCreatedSuccess: '¡Modalidad creada con éxito!',
      errorCreatingModality: 'Error al crear modalidad',
      planNameAndValueRequired: 'El nombre y valor del plan son obligatorios',
      planCreatedSuccess: '¡Plan creado con éxito!',
      errorCreatingPlan: 'Error al crear plan',
      announcementTitleAndContentRequired: 'El título y contenido del aviso son obligatorios',
      announcementPublishedSuccess: '¡Aviso publicado con éxito!',
      errorPublishingAnnouncement: 'Error al publicar aviso',
      nameNotInformed: 'Nombre no informado',
      emailNotInformed: 'Correo no informado',
      editPlan: 'Editar Plan',
      editAnnouncement: 'Editar Aviso',
      dateFormat: 'DD/MM/AAAA',

      // USER & ADMIN
      hello: 'Hola',
      admin: 'Admin',
      academyAdministrator: 'Administrador de la Academia',
      online: 'En línea',
      code: 'Código',

      // STATS
      totalStudents: 'Total de Estudiantes',
      activeStudents: 'Estudiantes Activos',

      // STUDENT DETAILS
      studentDetails: 'Detalles del Estudiante',
      phoneNotInformed: 'Teléfono no informado',
      addressNotInformed: 'Dirección no informada',
      registeredAt: 'Registrado en',
      enrolledClasses: 'Clases Matriculadas',
      details: 'Detalles',
      noClassesEnrolled: 'Ninguna clase matriculada',
      paymentHistory: 'Historial de Pagos',
      noPaymentsRegistered: 'Ningún pago registrado',
      viewAllPayments: 'Ver Todos los Pagos',
      actions: 'Acciones',
      editStudent: 'Editar Estudiante',
      addGraduation: 'Añadir Graduación',
      viewDetails: 'Ver Detalles',
      disassociate: 'Desasociar',
      suspended: 'Suspendido',
      beginner: 'Principiante',
      confirmDelete: 'Confirmar Eliminación',
      confirmDeleteStudent: '¿Está seguro de que desea eliminar al estudiante {name}?',
      studentDeletedSuccess: '¡Estudiante eliminado con éxito!',
      studentDeleteError: 'Error al eliminar estudiante',
      adjustSearchFilters: 'Ajuste los filtros de búsqueda',
      addFirstStudent: 'Añada el primer estudiante',
      paymentOK: 'Pago OK',
      pendingPaymentsCount: 'Pendientes',
      monthlyFinancials: 'Financiero del Mes',
      monthlyRevenue: 'Ingresos del Mes',
      pendingCount: 'Pendientes',
      overdueCount: 'Vencidos',
      alerts: 'Alertas',
      paymentsOverdue: 'pago(s) vencido(s)',
      manyPendingPayments: 'Muchos pagos pendientes',
      loadingAcademyInfo: 'Cargando información de la academia...',

      // ANNOUNCEMENTS
      announcements: 'Avisos',
      announcementBoard: 'Tablón de Avisos',
      noAnnouncementsNow: 'Ningún aviso en este momento',
      highPriority: 'Alta Prioridad',
      expiresOn: 'Expira el:',
      noExpirationDate: 'Sin fecha de expiración',

      // BELT LEVELS
      whiteBelt: 'Cinturón Blanco',
      yellowBelt: 'Cinturón Amarillo',
      orangeBelt: 'Cinturón Naranja',
      greenBelt: 'Cinturón Verde',
      blueBelt: 'Cinturón Azul',
      purpleBelt: 'Cinturón Morado',
      brownBelt: 'Cinturón Marrón',
      blackBelt: 'Cinturón Negro',
      blackBelt1: 'Cinturón Negro 1er Dan',
      blackBelt2: 'Cinturón Negro 2do Dan',
      blackBelt3: 'Cinturón Negro 3er Dan',
      blackBelt4: 'Cinturón Negro 4to Dan',
      blackBelt5: 'Cinturón Negro 5to Dan',

      // GRADUATION SCREEN
      newGraduation: 'Nueva Graduación',
      currentGraduation: 'Graduación Actual',
      graduationInfo: 'Información de Graduación',
      selectModality: 'Seleccionar Modalidad',
      responsibleInstructor: 'Instructor Responsable',
      selectInstructor: 'Seleccionar Instructor',
      newGraduationLabel: 'Nueva Graduación',
      selectGraduation: 'Seleccionar Graduación',
      additionalDetails: 'Detalles Adicionales',
      graduationDate: 'Fecha de Graduación',
      addGraduationNotesPlaceholder: 'Añadir notas sobre la graduación...',
      certificateNumberOptional: 'Número de Certificado (Opcional)',
      certificatePlaceholder: 'Ej: CERT-2024-001',
      saveGraduation: 'Guardar Graduación',
      loadingModalities: 'Cargando modalidades...',
      noModalitiesFound: 'No se encontraron modalidades',
      unnamedGraduation: 'Graduación sin nombre',
      noGraduationsAvailable: 'No hay graduaciones disponibles',
      loadingInstructors: 'Cargando instructores...',
      unnamedInstructor: 'Instructor sin nombre',
      noInstructorsFound: 'No se encontraron instructores',
      academyNotFoundLogin: 'Academia no encontrada. Inicie sesión nuevamente.',
      loadDataError: 'No se pudieron cargar los datos necesarios',
      selectGraduationError: 'Por favor, seleccione una graduación',
      selectModalityError: 'Por favor, seleccione una modalidad',
      selectInstructorError: 'Por favor, seleccione un instructor responsable',
      selectDateError: 'Por favor, seleccione una fecha',
      futureDateError: 'La fecha de graduación no puede ser futura',
      certificateFormatError: 'El formato del certificado debe ser: CERT-YYYY-NNN (ej: CERT-2024-001)',
      graduationAddedSuccess: '¡Graduación agregada con éxito!',
      selectModalityFirst: 'Seleccione una modalidad primero',
      invalidDate: 'Fecha inválida',
      selectDate: 'Seleccionar fecha',

      // PHYSICAL EVALUATION
      physicalEvaluation: 'Evaluación Física',
      newPhysicalEvaluation: 'Nueva Evaluación Física',
      editPhysicalEvaluation: 'Editar Evaluación Física',
      physicalEvaluationSubtitle: 'Registre sus medidas y siga su evolución física',
      basicMeasurements: 'Medidas Básicas',
      weightKg: 'Peso (kg)',
      heightCm: 'Altura (cm)',
      ageYears: 'Edad (años)',
      bmiTitle: 'Índice de Masa Corporal (IMC)',
      bioimpedanceOptional: 'Bioimpedancia (Opcional)',
      bodyFatPercent: 'Grasa Corporal (%)',
      muscleMassKg: 'Masa Muscular (kg)',
      boneMassKg: 'Masa Ósea (kg)',
      visceralFat: 'Grasa Visceral',
      basalMetabolismKcal: 'Metabolismo Basal (kcal)',
      bodyWaterPercent: 'Agua Corporal (%)',
      observations: 'Observaciones',
      optionalObservations: 'Observaciones (Opcional)',
      observationsPlaceholder: 'Ej: Inicio de nueva dieta, cambio en el entrenamiento, etc.',
      weightRequired: 'El peso es obligatorio',
      weightInvalid: 'El peso debe ser un número válido mayor que 0',
      heightRequired: 'La altura es obligatoria',
      heightInvalid: 'La altura debe ser un número válido mayor que 0',
      ageRequired: 'La edad es obligatoria',
      ageInvalid: 'La edad debe ser un número válido entre 1 y 120',
      bodyFatInvalid: 'El porcentaje de grasa debe estar entre 0 y 100',
      muscleMassInvalid: 'La masa muscular debe ser un número válido mayor que 0',
      bodyWaterInvalid: 'El porcentaje de agua debe estar entre 0 y 100',
      academyNotIdentified: 'Error: Academia no identificada. Inicie sesión nuevamente.',
      evaluationUpdatedSuccess: '¡Evaluación física actualizada con éxito!',
      evaluationSavedSuccess: '¡Evaluación física guardada con éxito!',
      evaluationSaveError: 'Error al guardar la evaluación física. Intente nuevamente.',
      underweight: 'Bajo peso',
      normalWeight: 'Peso normal',
      overweight: 'Sobrepeso',
      obesityI: 'Obesidad grado I',
      obesityII: 'Obesidad grado II',
      obesityIII: 'Obesidad grado III',
      currentEvaluation: 'Evaluación Actual',
      progress: 'Progreso',
      vsPreviousEvaluation: 'vs. evaluación anterior',
      evolution: 'Evolución',
      evaluationHistory: 'Historial de Evaluaciones',
      noEvaluationsFound: 'Ninguna evaluación física encontrada',
      startEvaluationPrompt: 'Realice su primera evaluación para comenzar a seguir su evolución',
      newEvaluation: 'Nueva Evaluación',

      // MESSAGES
      functionalityInDevelopment: 'Funcionalidad en desarrollo',
      errorLoadingAnnouncements: 'Error al cargar avisos',
      errorLoadingData: 'Error al cargar datos',
      couldNotLoadAnnouncements: 'No se pudieron cargar los avisos. Intente nuevamente más tarde.',
      loadingInstructorDashboard: 'Cargando panel del instructor',
      loadingStudentDashboard: 'Cargando panel del estudiante',
      loadingAdminDashboard: 'Cargando panel del administrador',
      studentsLoaded: 'Estudiantes cargados',
      errorSearchingStudents: 'Error al buscar estudiantes',
      errorFormattingDate: 'Error al formatear fecha',
      couldNotLoadData: 'No se pudieron cargar los datos. Intente nuevamente.',
      tryAgainLater: 'Intente nuevamente más tarde',

      // MONTHS ABBREVIATED
      janShort: 'ENE',
      febShort: 'FEB',
      marShort: 'MAR',
      aprShort: 'ABR',
      mayShort: 'MAY',
      junShort: 'JUN',
      julShort: 'JUL',
      augShort: 'AGO',
      sepShort: 'SEP',
      octShort: 'OCT',
      novShort: 'NOV',
      decShort: 'DIC',

      // AUTH/LOGIN
      welcome: '¡Bienvenido de nuevo!',
      password: 'Contraseña',
      login: 'Entrar',
      forgotPassword: '¿Olvidó su contraseña?',
      orLoginWith: 'O inicie sesión con',
      noAccount: '¿No tiene una cuenta?',
      register: 'Registrarse',
      loggingIn: 'Iniciando sesión',
      loginSuccess: '¡Inicio de sesión exitoso!',
      googleLoginSuccess: '¡Inicio de sesión con Google exitoso!',
      facebookLoginSuccess: '¡Inicio de sesión con Facebook exitoso!',
      microsoftLoginSuccess: '¡Inicio de sesión con Microsoft exitoso!',
      appleLoginSuccess: '¡Inicio de sesión con Apple exitoso!',
      invalidEmail: 'Correo inválido',
      passwordTooShort: 'Contraseña demasiado corta',
      passwordMinChars: 'La contraseña debe tener al menos 6 caracteres',
      fillAllFields: 'Complete todos los campos',
      googleLoginError: 'Error al iniciar con Google',
      facebookLoginError: 'Error al iniciar con Facebook',
      appleLoginError: 'Error al iniciar con Apple',
      microsoftLoginError: 'Error al iniciar con Microsoft',

      // REGISTER
      createAccount: 'Crear cuenta',
      fillDataToRegister: 'Complete sus datos para comenzar',
      personalData: 'Datos personales',
      fullName: 'Nombre Completo',
      phoneWhatsApp: 'Teléfono / WhatsApp',
      userType: 'Tipo de usuario',
      studentDescription: 'Acceda a entrenamientos y siga su progreso',
      instructorDescription: 'Gestione clases y estudiantes',
      administrator: 'Administrador',
      adminDescription: 'Gestión completa del gimnasio',
      passwordSection: 'Seguridad',
      confirmPassword: 'Confirmar Contraseña',
      alreadyHaveAccount: '¿Ya tiene una cuenta?',
      signIn: 'Entrar',
      creatingAccount: 'Creando su cuenta',
      accountCreatedSuccess: '¡Cuenta creada con éxito!',
      registrationError: 'Error al crear la cuenta',
      nameRequired: 'El nombre es obligatorio',
      emailRequired: 'El correo es obligatorio',
      passwordMinLength: 'Mínimo de 6 caracteres',
      passwordsMismatch: 'Las contraseñas no coinciden',
      registrationDevelopment: 'Registro en desarrollo',
      acceptTermsRequired: 'Debe aceptar los términos de uso',
      acceptPrivacyRequired: 'Debe aceptar la política de privacidad',
      acceptThe: 'Acepto los',
      acceptPrivacy: 'Acepto la',
      termsOfUse: 'Términos de Uso',
      privacyPolicy: 'Política de Privacidad',
      emailAlreadyInUse: 'Este correo ya está registrado. Inicie sesión o use otro correo.',
      weakPassword: 'Contraseña muy débil. Use al menos 6 caracteres.',
      invalidEmailFormat: 'Correo inválido. Verifique el formato.',

      // PASSWORD RECOVERY
      recoverPassword: 'Recuperar contraseña',
      enterEmailForInstructions: 'Ingrese su correo para recibir instrucciones',
      pleaseValidEmail: 'Por favor, ingrese un correo válido',
      sendEmail: 'Enviar correo',
      emailSent: 'Correo enviado',
      emailSentSuccess: '¡Correo de recuperación enviado con éxito!',
      checkInboxInstructions: 'Verifique su bandeja de entrada para las instrucciones',
      spamFolderWarning: 'No olvide verificar la carpeta de spam',
      backToLogin: 'Volver al login',
      resetPasswordError: 'Error al enviar el correo de recuperación',
      emailNotFound: 'Correo no encontrado',
      tooManyRequests: 'Demasiadas solicitudes. Intente más tarde.',
      configurationNotFound: 'Configuración no encontrada',
      contactSupport: 'Contacte con el soporte',

      // INVITES
      invite: 'Invitación',
      invites: 'Invitaciones',
      inviteCode: 'Código de invitación',
      inviteToken: 'Token de invitación',
      inviteRequired: 'El código de invitación es obligatorio',
      inviteInvalid: 'Código de invitación inválido o ya utilizado',
      inviteExpired: 'Esta invitación ha expirado',
      inviteAccepted: 'Invitación aceptada con éxito',
      inviteProcessingError: 'Error al procesar la invitación',
      inviteUnauthenticated: 'El usuario debe estar autenticado para usar una invitación',
      inviteNotFound: 'Invitación no encontrada',
      inviteAlreadyUsed: 'Esta invitación ya ha sido utilizada',
      sendInvite: 'Enviar invitación',
      createInvite: 'Crear invitación',
      acceptInvite: 'Aceptar invitación',
      invitationSent: 'Invitación enviada',
      invitationAccepted: 'Invitación aceptada',
    }
  }
};

// Helper functions
export const getString = (key: string, language: LanguageCode = 'pt'): string => {
  try {
    return languages[language]?.strings?.[key] || key;
  } catch (error) {
    console.warn(`Translation key "${key}" not found for language "${language}"`);
    return key;
  }
};

export const getLanguages = (): { code: LanguageCode; name: string; flag: string }[] => {
  return (Object.keys(languages) as LanguageCode[]).map((code) => ({
    code,
    name: languages[code].name as string,
    flag: languages[code].flag as string,
  }));
};

export const isLanguageSupported = (language: string): language is LanguageCode => {
  return (Object.keys(languages) as string[]).includes(language);
};

// Temas básicos usando design tokens
export const lightTheme: { colors: Record<string, string> } = {
  colors: {
    primary: COLORS.primary[500],
    primaryVariant: COLORS.primary[700],
    secondary: COLORS.secondary[500],
    background: LIGHT_THEME.background.default,
    surface: LIGHT_THEME.background.paper,
    card: LIGHT_THEME.background.paper,
    text: LIGHT_THEME.text.primary,
    accent: COLORS.info[500],
    textSecondary: LIGHT_THEME.text.secondary,
    textDisabled: LIGHT_THEME.text.disabled,
  }
};

export const darkTheme: { colors: Record<string, string> } = {
  colors: {
    primary: COLORS.primary[400],
    primaryVariant: COLORS.primary[300],
    secondary: COLORS.secondary[400],
    background: COLORS.gray[900],
    surface: COLORS.gray[800],
    card: COLORS.gray[800],
    text: COLORS.white,
    accent: COLORS.info[400],
    textSecondary: COLORS.gray[300],
    textDisabled: COLORS.gray[500],
  }
};

// Função para obter tema baseado no tipo de usuário
export const getThemeForUserType = (
  userType: 'student' | 'instructor' | 'admin' = 'student',
  isDarkMode: boolean = false
): { colors: Record<string, string>; userType: string; isDarkMode: boolean } => {
  const baseTheme = isDarkMode ? darkTheme : lightTheme;

  // Cores específicas por tipo de usuário usando design tokens
  const userColors = {
    student: {
      primary: isDarkMode ? COLORS.info[400] : COLORS.primary[500],
      accent: isDarkMode ? COLORS.info[300] : COLORS.info[500],
    },
    instructor: {
      primary: isDarkMode ? COLORS.secondary[400] : COLORS.secondary[600],
      accent: isDarkMode ? COLORS.secondary[300] : COLORS.secondary[500],
    },
    admin: {
      primary: isDarkMode ? COLORS.primary[400] : COLORS.primary[700],
      accent: isDarkMode ? COLORS.primary[300] : COLORS.primary[600],
    }
  };

  const colors = userColors[userType] || userColors.student;

  return {
    ...baseTheme,
    colors: {
      ...baseTheme.colors,
      primary: colors.primary,
      accent: colors.accent,
    },
    userType,
    isDarkMode
  };
};

export default languages;
