name: Build PR Preview

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  build-preview:
    name: Build Preview APK
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: 🏗 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🏗 Setup EAS CLI
        run: |
          npm install -g @expo/cli@latest eas-cli@latest
          echo "EAS CLI installed successfully"
        
      - name: 🔑 Authenticate EAS
        run: |
          echo "Checking EAS authentication..."
          eas whoami
          echo "EAS authentication successful"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: |
          echo "Installing project dependencies..."
          npm ci
          echo "Dependencies installed successfully"

      - name: 🔧 Configure EAS project
        run: |
          echo "Checking EAS project configuration..."
          if [ ! -f "eas.json" ]; then
            echo "eas.json not found, configuring project..."
            eas build:configure --platform android --non-interactive
          else
            echo "eas.json found, project already configured"
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🔧 Setup environment variables
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          echo "EXPO_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
          echo "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
          echo "EXPO_PUBLIC_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
          echo "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
          echo "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
          echo "EXPO_PUBLIC_FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env

      - name: ✅ Run tests
        run: npm run test:ci

      - name: 🔍 Type check
        run: npm run type-check

      - name: 🎨 Lint check
        run: npm run lint

      - name: 🚀 Build Preview APK
        run: eas build --platform android --profile preview --non-interactive --message "PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}"

      - name: 📱 Get build info
        id: build-info
        run: |
          # Aguardar processamento inicial
          sleep 30
          
          BUILD_INFO=$(eas build:list --platform android --limit 1 --json --non-interactive)
          BUILD_ID=$(echo $BUILD_INFO | jq -r '.[0].id')
          BUILD_STATUS=$(echo $BUILD_INFO | jq -r '.[0].status')
          
          echo "build-id=$BUILD_ID" >> $GITHUB_OUTPUT
          echo "build-status=$BUILD_STATUS" >> $GITHUB_OUTPUT
          
          echo "Build ID: $BUILD_ID"
          echo "Status inicial: $BUILD_STATUS"

      - name: 💬 Comment PR with build info
        uses: actions/github-script@v7
        with:
          script: |
            const buildId = '${{ steps.build-info.outputs.build-id }}';
            const buildStatus = '${{ steps.build-info.outputs.build-status }}';
            const prNumber = context.issue.number;
            const commitSha = context.sha.substring(0, 7);
            
            const comment = `
            ## 📱 Preview Build Android
            
            **PR:** #${prNumber} - ${{ github.event.pull_request.title }}
            **Commit:** \`${commitSha}\`
            **Build ID:** \`${buildId}\`
            **Status:** ${buildStatus === 'in-queue' ? '🟡 Na fila' : buildStatus === 'in-progress' ? '🔄 Em andamento' : buildStatus}
            
            ### 📋 Verificações
            - ✅ Testes passaram
            - ✅ Type check passou  
            - ✅ Lint passou
            - 🚀 Build iniciado
            
            ### 📥 Download
            ${buildStatus === 'finished' ? 
              '**APK pronto!** Verifique o link de download no [Expo Dashboard](https://expo.dev/accounts/c1c3ru/projects/academia-app/builds)' : 
              '**Build em andamento...** Acompanhe o progresso no [Expo Dashboard](https://expo.dev/accounts/c1c3ru/projects/academia-app/builds/' + buildId + ')'
            }
            
            ---
            *Build automático para preview do PR*
            `;
            
            // Verificar se já existe um comentário de build
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            
            const existingComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('## 📱 Preview Build Android')
            );
            
            if (existingComment) {
              // Atualizar comentário existente
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: comment
              });
            } else {
              // Criar novo comentário
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: comment
              });
            }

  build-status-check:
    name: Build Status Check
    runs-on: ubuntu-latest
    needs: build-preview
    if: always()
    
    steps:
      - name: ✅ Build Success
        if: needs.build-preview.result == 'success'
        run: |
          echo "✅ Preview build iniciado com sucesso!"
          echo "🔗 Acompanhe em: https://expo.dev/accounts/c1c3ru/projects/academia-app/builds"

      - name: ❌ Build Failed
        if: needs.build-preview.result == 'failure'
        run: |
          echo "❌ Preview build falhou!"
          echo "Verifique os logs acima para detalhes."
          exit 1

      - name: ⚠️ Build Skipped
        if: needs.build-preview.result == 'skipped'
        run: |
          echo "⚠️ Preview build foi pulado (PR draft ou outras condições)"
